apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: owlvey
    tier: state  
  name: owlvey-state-local-deployment
  namespace: owlvey
spec:
  replicas: 1
  selector:
    matchLabels:
        key: owlvey-relational-pod
  template:
    metadata:
      labels:
        key: owlvey-relational-pod
    spec:
      containers:
        - name: db
          image: owlvey/relational:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 1433
          env:
            - name: "SA_PASSWORD"
              value: "TheFalcon123"
            - name: "ACCEPT_EULA"
              value: "Y"
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "docker"
            - name: "MSSQL_PID"
              value: "Express"