name: Build API Image

on:
  push:
    branches: [ develop ]    

jobs:    
    build:      
      name: Build 
      runs-on: ubuntu-latest
      steps:        
        - uses: actions/checkout@v2                           
        - name: docker compose build                  
          working-directory: ./containers/api
          run: docker-compose build
        - name: docker login
          run: docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
        - name: docker tag
          run: |
            docker tag registry/api owlveydevcommit/api:latest
            docker tag registry/api owlveydevcommit/api:${{ github.sha }}                  
            docker push owlveydevcommit/api
    